<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
	<LangVersion>7.3</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <BaseOutputPath>C:\Users\minas\Desktop\Нулевая ошибка\error\Assets\Dialog</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
	<PackageReference Include="System.Runtime" Version="4.3.0" />
  </ItemGroup>
</Project>
